# Investigación

La investigación del Área se centra en el estudio de las condiciones competitivas del aparato productivo mexicano en un contexto globalizado desde una perspectiva sectorial y espacial.

El trabajo de investigación se desarrolla de forma articulada, a partir de los trabajos y líneas de sus miembros que tienen en común el estudio desde una perspectiva sistémica de los procesos de innovación, desde una perspectiva territorial e institucional.

__[Publicaciones](https://rpm-uam.blogspot.com/p/articulos.html)__

__[Tesinas](https://rpm-uam.blogspot.com/p/tesinas.html)__

#### __Algunas de las líneas de investigación actualmente en marcha de los miembros del Área son:__

- El sector agroexportador en México, 1990-2018: modalidades, estructura, articulación y localización (Dr. Edmar Salinas Callejas).
- Análisis del desarrollo regional industrial desde una perspectiva regulacionista: conformación y estabilidad de los espacios (Dra. Paloma Sánchez Cruz).
- Productividad y desarrollo regional en las concentraciones industriales de México (Dr. Jaime Prudencio).
- Ventajas competitivas, redes de conocimiento e innovación en la Región Centro de México (Dra. Mónica de la Garza).
- Cadenas globales de valor en México: el sector aeroespacial en Querétaro (Mtro. Alejandro Buendía).
- Evolución y trayectorias industriales en las zonas metropolitanas de México (Dr.  Andrés Godínez Enciso).

#### __Servicio Social__

__[Proyectos de Investigación Servicio Social](https://rpm-uam.blogspot.com/p/proyectos-de-investigacion-servicio.html)__

Si cuentas con 70% de tus créditos académicos y tienes interés en los diferentes ejes temáticos que se manejan en el Área, envíanos un correo a rpm.azc@gmail.com para darte la información referente a los proyectos de investigación actualmente en marcha y a los que te podrías sumar.

Es importante que revises también la página de [Servicios Escolares](http://serviciosocialdcsh.azc.uam.mx/index.php/tramites-2/inscripcion-del-servicio-social) para conocer el proceso administrativo.
